dist: xenial

language: python

python:
  - "3.8"  # note that version really set in `environment.yml` though

# from here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - conda activate barcoded_flu_pdmH1N1

script: 
  - bash ./lint.bash

branches:
  only:
    - main
    - snakemake_lint
