# YAML configuration file for the analysis

# max CPUs used by any rules
max_cpus: 16

# output directories
fastq10x_dir: results/fastq10x  # FASTQs & QC 10x transcriptomic runs
mkfastq10x_dir: results/fastq10x/mkfastq_output  # `cellranger mkfastq` output
genome_dir: results/genomes  # location of downloaded genomes and annotations
refgenome: results/genomes/refgenome  # STAR reference genome directory
aligned_fastq10x_dir: results/aligned_fastq10x  # aligned 10x transcriptomic reads
viral_fastq10x_dir: results/viral_fastq10x  # viral tags / barcodes in 10x transcriptomics
#analysis_dir: results/analysis  # fine-grained analyses

# cellular genome and GTF ftp sites
cell_genome_ftp: ftp://ftp.ensembl.org/pub/release-98/fasta/canis_familiaris/dna/Canis_familiaris.CanFam3.1.dna.toplevel.fa.gz
cell_gtf_ftp: ftp://ftp.ensembl.org/pub/release-98/gtf/canis_familiaris/Canis_familiaris.CanFam3.1.98.gtf.gz

# viral genome and transcript information
viral_genome: data/flu_sequences/flu-CA09.fasta
viral_gtf: data/flu_sequences/flu-CA09.gtf
viral_genbank: data/flu_sequences/flu-CA09.gb
viral_tag_identities: data/flu_sequences/flu-CA09_viral_tags.yaml

# STAR alignment parameters for transcriptomics. Reduce the penalty for
# non-canonical splice sites, which is probably bad for mapping cellular
# reads but is good for mapping viral reads which will have deletions
# not corresponding to splice sites.
scoreGapNoncan: -4
scoreGapGCAG: -4
scoreGapATAC: -4

# URL location of 10X barcode whitelist: **this is for the v3 kit**
cb_whitelist_10x_url: https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz
cb_whitelist_10x: results/aligned_fastq10x/cb_whitelist_10x.txt

cb_len_10x: 16  # length of 10X cell barcode
umi_len_10x: 12  # length of 10X UMI: **this is for the v3 kit**


#----------------------------------------------------------------------------
#                    configuration of experiments
#----------------------------------------------------------------------------
experiments:

  hashing_wt_rapidpilot:
    description: Single-cell transcriptomics using a small-scale pilot rescue
                 of the wildtype viral tag variant.
    lab_notes: https://benchling.com/s/etr-Q28fCd1kprRNxAd0v5Hg
    expect_ncells: 2000
    transcriptomics:
      2019-12-03:
        index: SI-GA-A3
        bcl_folder: /shared/ngs/illumina/bloom_lab/191203_M03100_0504_000000000-CNCN9/
        lane: '*'

  hashing_trial1:
    description: Single-cell transcriptomics using the wildtype and dblSyn viral
                 tag variants. Infection volume was chosen based on HA expression
                 measured by flow cytometry.
    lab_notes: https://benchling.com/s/etr-i9I0yHiFb0P8wHCxosim
    expect_ncells: 2000
    transcriptomics:
      2020-01-16:
        index: SI-GA-A4
        bcl_folder: /shared/ngs/illumina/bloom_lab/200128_M03100_0528_000000000-CRC4G/
        lane: '*'
      2020-02-18:
        index: SI-GA-A4
        bcl_folder: /shared/ngs/illumina/bloom_lab/200218_D00300_0910_AHCHHJBCX3/Raw/
        lane: 2

  hashing_trial2:
    description: Single-cell transcriptomics using the wildtype and dblySyn viral
                 tag variants. Infection volume was chosen based on the results
                 of `hashing_trial1` and flow cytometry. The incolum volume for
                 the wildtype tag variant was about 12-fold higher, and for the
                 dblSyn tag variant was about 24-fold higher.
    lab_notes: https://benchling.com/s/etr-W8urOmOAQ7L6U4HAXMNy
    expect_ncells: 5000
    transcriptomics:
      2020-06-02:
        index: SI-GA-B3
        bcl_folder: /home/solexa/ngs/illumina/bloom_lab/200602_M03100_0578_000000000-J3464/
        lane: '*'
      2020-07-01:
        index: SI-GA-B3
        bcl_folder: /shared/ngs/illumina/agreaney/200701_D00300_0988_BHGFGMBCX3/raw/200701_D00300_0988_BHGFGMBCX3/
        lane: 2
      2020-08-26:
        index: SI-GA-B3
        bcl_folder: /shared/ngs/illumina/bloom_lab/bloom_lab/200826_D00300_1040_BHHGLWBCX3/raw/200826_D00300_1040_BHHGLWBCX3/
        lane: '*'

  hashing_trial3_withNH4Cl:
    description: Single-cell transcriptomics using the wildtype and dblSyn viral
                 tag variants at a high MOI. Infection volume was based on the results of
                 `hashing_trial2`.
    lab_notes: https://benchling.com/s/etr-ToK66qT0Mfmf6FsexKo4
    expect_ncells: 5000
    transcriptomics:
      2020-07-24:
        index: SI-GA-B5
        bcl_folder: /shared/ngs/illumina/bloom_lab/200724_M03100_0593_000000000-J33YK/
        lane: '*'
      2020-08-26:
        index: SI-GA-B5
        bcl_folder: /shared/ngs/illumina/bloom_lab/bloom_lab/200826_D00300_1040_BHHGLWBCX3/raw/200826_D00300_1040_BHHGLWBCX3/
        lane: '*'

  hashing_trial3_noNH4Cl:
    description: Single-cell transcriptomics performed *without* NH4Cl treatment. Used
                 wildtype and dblSyn viral tag variants at high MOI. Infection volume was
                 based on the results of `hashing_trial2`. Performed in conjunction with
                 `hashing_trial3_withNH4Cl`.
    lab_notes: https://benchling.com/s/etr-ToK66qT0Mfmf6FsexKo4
    expect_ncells: 5000
    transcriptomics:
      2020-07-24:
        index: SI-GA-B4
        bcl_folder: /shared/ngs/illumina/bloom_lab/200724_M03100_0593_000000000-J33YK/
        lane: '*'

  scProgenyProduction_trial1:
    description: Single-cell transcriptomics performed on low MOI-infected sample.
                 Innoculum volumes based on `hashing_trial2` data. Loaded
                 all collected cells from two 24-well wells, each infected with either
                 wildtype or dblySn viral tag variants.
    lab_notes: https://benchling.com/s/etr-20lOO7l1FdEJJIpxV6vD
    expect_ncells: 10000
    transcriptomics:
      2020-09-25:
        index: SI-GA-B8
        bcl_folder: /shared/ngs/illumina/bloom_lab/200925_D00300_1065_AHHL7NBCX3/raw/200925_D00300_1065_AHHL7NBCX3/
        lane: 2
    viral_barcodes:
      supernatant:
        wt:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-Sup-fluHA-A_S1_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-Sup-fluHA-B_S2_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-Sup-fluNA-A_S17_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-Sup-fluNA-B_S18_L001_R1_001.fastq.gz
        syn:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-Sup-fluHA-A_S3_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-Sup-fluHA-B_S4_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-Sup-fluNA-A_S19_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-Sup-fluNA-B_S20_L001_R1_001.fastq.gz
      second_infection:
        wt:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-SecondInf-fluHA-A_S5_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-SecondInf-fluHA-B_S6_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-SecondInf-fluNA-A_S21_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-WT-SecondInf-fluNA-B_S22_L001_R1_001.fastq.gz
        syn:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-SecondInf-fluHA-A_S7_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-SecondInf-fluHA-B_S8_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-SecondInf-fluNA-A_S23_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial1-dblSyn-SecondInf-fluNA-B_S24_L001_R1_001.fastq.gz
      

  scProgenyProduction_trial2:
    description: Single-cell transcriptomics performed on low MOI-infected sample.
                 Innoculum volumes based on `hashing_trial2` data. Loaded
                 all collected cells from two 24-well wells, each infected with either
                 wildtype or dblySn viral tag variants.
    lab_notes: https://benchling.com/s/etr-73UD4Mx8uXn1xcxlV1ym
    expect_ncells: 10000
    transcriptomics:
      2020-09-25:
        index: SI-GA-B9
        bcl_folder: /shared/ngs/illumina/bloom_lab/200925_D00300_1065_AHHL7NBCX3/raw/200925_D00300_1065_AHHL7NBCX3/
        lane: '*'
    viral_barcodes:
      supernatant:
        wt:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-Sup-fluHA-A_S9_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-Sup-fluHA-B_S10_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-Sup-fluNA-A_S25_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-Sup-fluNA-B_S26_L001_R1_001.fastq.gz
        syn:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-Sup-fluHA-A_S11_L001_R1_001.fastq.gz 
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-Sup-fluHA-B_S12_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-Sup-fluNA-A_S27_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-Sup-fluNA-B_S28_L001_R1_001.fastq.gz
      second_infection:
        wt:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-SecondInf-fluHA-A_S13_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-SecondInf-fluHA-B_S14_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-SecondInf-fluNA-A_S29_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-WT-SecondInf-fluNA-B_S30_L001_R1_001.fastq.gz
        syn:
          fluHA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-SecondInf-fluHA-A_S15_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-SecondInf-fluHA-B_S16_L001_R1_001.fastq.gz
          fluNA:
            replicate_1: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-SecondInf-fluNA-A_S31_L001_R1_001.fastq.gz
            replicate_2: /shared/ngs/illumina/bloom_lab/201013_M03100_0625_000000000-JB2KP/Data/Intensities/BaseCalls/Trial2-dblSyn-SecondInf-fluNA-B_S32_L001_R1_001.fastq.gz
