# YAML configuration file for the analysis

# max CPUs used by any rules
max_cpus: 16

# file specifying 10X Illumina runs
illumina_runs_10x: data/illumina_runs_10x.csv

# output directories
fastq10x_dir: results/fastq10x  # FASTQ files for 10X Illumina runs
mkfastq10x_dir: results/mkfastq10x_output  # output of 10X `cellranger mkfastq`
genome_dir: results/ref_genomes # Automatically-downloaded reference genomes for canine and human
log_dir: results/logs

# params for parsing 10X FASTQ R1 termini in `parse_fastq10x_termini` rule
fastq10x_trim5: 22  # trim this much off 5' end of R1 reads that match patterns
fastq10x_multi_pattern: first  # when matching multi patterns, how to assign?
fastq10x_patterns:  # names, regex, allowed substitution mismatches
  - [early-viral-priming,
     'CTACACGACGCTCTTCCGATCT[ACGT]{16}GCGGCCGCCTAT',
     2]
  - [proper-cell-barcode,
     'CTACACGACGCTCTTCCGATCT[ACGT]{26}T{2}',
     2]

# params for downloading reference genomes
# species, genome name, ftp link
spikein_genome:
  species: human
  fasta: ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  gtf: ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz

cell_genome:
  species: canine
  fasta: ftp://ftp.ensembl.org/pub/release-98/fasta/canis_familiaris/dna/Canis_familiaris.CanFam3.1.dna.toplevel.fa.gz
  gtf: ftp://ftp.ensembl.org/pub/release-98/gtf/canis_familiaris/Canis_familiaris.CanFam3.1.98.gtf.gz
