# YAML configuration file for the analysis

# max CPUs used by any rules
max_cpus: 16

# file specifying 10X Illumina runs
illumina_runs_10x: data/illumina_runs_10x.csv

# output directories
fastq10x_dir: results/fastq10x  # FASTQ files & QC stats for 10X Illumina runs
mkfastq10x_dir: results/fastq10x/mkfastq_output  # `cellranger mkfastq` output
genome_dir: results/genomes  # location of downloaded genomes and annotations
refgenome: results/genomes/refgenome  # STAR reference genome directory

# cellular genome and GTF ftp sites
cell_genome_ftp: ftp://ftp.ensembl.org/pub/release-98/fasta/canis_familiaris/dna/Canis_familiaris.CanFam3.1.dna.toplevel.fa.gz
cell_gtf_ftp: ftp://ftp.ensembl.org/pub/release-98/gtf/canis_familiaris/Canis_familiaris.CanFam3.1.98.gtf.gz

# viral genome and GTF file locations
viral_genome: data/flu_sequences/flu-CA09.fasta
viral_gtf: data/flu_sequences/flu-CA09.gtf

# params for parsing 10X FASTQ R1 termini in `parse_fastq10x_termini` rule
fastq10x_trim5: 22  # trim this much off 5' end of R1 reads that match patterns
fastq10x_multi_pattern: first  # when matching multi patterns, how to assign?
fastq10x_patterns:  # names, regex, allowed substitution mismatches
  - [early-viral-priming,
     'CTACACGACGCTCTTCCGATCT[ACGT]{16}GCGGCCGCCTAT',
     2]
  - [proper-cell-barcode,
     'CTACACGACGCTCTTCCGATCT[ACGT]{26}T{2}',
     2]
