# YAML configuration file for the analysis

# max CPUs used by any rules
max_cpus: 16

# output directories
log_dir: results/logs  # logs for snakemake rules
fastq10x_dir: results/fastq10x  # FASTQs & QC 10x transcriptomic runs
pacbio_dir: results/pacbio # FASTQs for pacBio runs
mkfastq10x_dir: results/fastq10x/mkfastq_output  # `cellranger mkfastq` output
genome_dir: results/genomes  # location of downloaded genomes and annotations
refgenome: results/genomes/refgenome  # STAR reference genome directory
aligned_fastq10x_dir: results/aligned_fastq10x  # aligned 10x transcriptomic reads
viral_fastq10x_dir: results/viral_fastq10x  # viral tags / barcodes in 10x transcriptomics
viral_tags_bcs_in_cells_dir: results/viral_tags_bcs_in_cells  # calling viral tags / barcodes by cell
viral_progeny_dir: results/viral_progeny  # viral barcodes from progeny
align_and_parse_dir: results/pacbio/CA09_align_and_parse #pacbio alignment and parsing output


# cellular genome and GTF ftp sites
cell_genome_ftp: ftp://ftp.ensembl.org/pub/release-98/fasta/canis_familiaris/dna/Canis_familiaris.CanFam3.1.dna.toplevel.fa.gz
cell_gtf_ftp: ftp://ftp.ensembl.org/pub/release-98/gtf/canis_familiaris/Canis_familiaris.CanFam3.1.98.gtf.gz

# viral genome and transcript information
viral_genome: data/flu_sequences/flu-CA09.fasta
viral_gtf: data/flu_sequences/flu-CA09.gtf
viral_genbank: data/flu_sequences/flu-CA09.gb
viral_tag_identities: data/flu_sequences/flu-CA09_viral_tags.yaml
viral_amplicons: data/flu_sequences/pacbio_amplicons/fluCA09.gb
amplicon_features: data/flu_sequences/pacbio_amplicons/fluCA09_features.yaml
amplicon_linearization_primers: data/flu_sequences/pacbio_amplicons/linearization_primers.tsv
amplicon_to_reference: data/flu_sequences/pacbio_amplicons/amplicon_to_reference.csv

# STAR alignment parameters for transcriptomics. Reduce the penalty for
# non-canonical splice sites, which is probably bad for mapping cellular
# reads but is good for mapping viral reads which will have deletions
# not corresponding to splice sites.
scoreGapNoncan: -4
scoreGapGCAG: -4
scoreGapATAC: -4

# URL location of 10X barcode whitelist: **this is for the v3 kit**
cb_whitelist_10x_url: https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz
cb_whitelist_10x: results/aligned_fastq10x/cb_whitelist_10x.txt

cb_len_10x: 16  # length of 10X cell barcode
umi_len_10x: 12  # length of 10X UMI: **this is for the v3 kit**

# Number of Median Absolute Deviations to use for filtering total UMIs per cell
total_UMI_deviations: 2.5

# Fraction of viral UMIs required to call cell as infected
infection_threshold: 0.01

# False discovery rate for assigning viral tags based on expected
# viral tag counts in uninfected cells.
viral_tag_fdr: 0.0001

# viral barcode parsing paremeters for supernatant and second
# infection sequencing. 
viral_barcode_upstream_length: 28  # Specify the length of upstream seq used to check identity
viral_barcode_mismatch: 0  # Number of mismatches allowed in upstream seq
viral_barcode_minq: 30  # Minimum quality threshold for bases in viral barcode

# Detection limit for supernatant and second infection sequencing
progeny_detection_limit: 1e-5

# False discovery rate for calling viral barcodes based on expected
# viral tag counts in uninfected cells.
viral_bc_fdr: 0.0001

# Parameters for building PacBio CCSs
ccs_min_length: 50
ccs_max_length: 5000
ccs_min_rq: 0.999

#----------------------------------------------------------------------------
#                    configuration of experiments
#----------------------------------------------------------------------------
experiments:

  scProgenyProduction_trial3:
    description: Single-cell transcriptomics performed on even lower MOI-infected
                 sample. Innoculum volumes based on `scProgenyProduction_trial1` and
                 `scProgenyProduction_trial2` data. Loaded all collected cells from
                 two 24-well wells, each infected with either wildtype or dblySn
                 viral tag variants.
    lab_notes: https://benchling.com/s/etr-N4laiIAy3AUePJdig7wR
    expect_ncells: 10000
    transcriptomics:
      2021-03-12:
        index: SI-TT-A3
        bcl_folder: /shared/ngs/illumina/bloom_lab/210312_D00300_1192_BHKHNYBCX3/raw/210312_D00300_1192_BHKHNYBCX3/
        lane: 1
        index_sequencing: single
      2021-04-09:
        index: SI-TT-A3
        bcl_folder: /shared/ngs/illumina/bloom_lab/210409_D00300_1210_BHKC7KBCX3/raw/210409_D00300_1210_BHKC7KBCX3/
        lane: '*'
        index_sequencing: single
      2021-08-25:
        index: SI-TT-A3
        bcl_folder: /shared/ngs/illumina/bloom_lab/210825_D00300_1310_BHMH5TBCX3/raw/210825_D00300_1310_BHMH5TBCX3/
        lane: '*'
        index_sequencing: none
      2021-09-15:
        index: SI-TT-A3
        bcl_folder: /shared/ngs/illumina/bloom_lab/210915_VH00699_2_AAAMCL7M5/raw/210915_VH00699_2_AAAMCL7M5/
        lane: '*'
        index_sequencing: none
    pacbio_viral_sequencing:
      2021-08-05_all_segments_run1: /fh/fast/bloom_j/SR/ngs/pacbio/210730_SequelIIe/r64272e_20210730_182729/1_A01/m64272e_210730_193026.subreads.bam
      2021-09-17_all_segments_run2: /fh/fast/bloom_j/SR/ngs/pacbio/210917_SequelIIe/r64272e_20210917_174421/1_A01/m64272e_210917_175514.subreads.bam

    viral_barcodes:
      supernatant:
        wt:
          fluHA:
            replicate_1:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/WT-sup-fluHA-rep1_S9_L001_R1_001.fastq.gz
            replicate_2:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/WT-sup-fluHA-rep2_S13_L001_R1_001.fastq.gz
          fluNA:
            replicate_1:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/WT-sup-fluNA-rep1_S1_L001_R1_001.fastq.gz
            replicate_2:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/WT-sup-fluNA-rep2_S1_L001_R1_001.fastq.gz
        syn:
          fluHA:
            replicate_1:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/dblSyn-sup-fluHA-rep1_S10_L001_R1_001.fastq.gz
            replicate_2:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/dblSyn-sup-fluHA-rep2_S14_L001_R1_001.fastq.gz
          fluNA:
            replicate_1:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/dblSyn-sup-fluNA-rep1_S2_L001_R1_001.fastq.gz
            replicate_2:
              2021-04-08: /shared/ngs/illumina/bloom_lab/210408_M04866_0464_000000000-JL5M4_new-demux/Data/Intensities/BaseCalls/dblSyn-sup-fluNA-rep2_S6_L001_R1_001.fastq.gz
      second_infection:
        wt:
          fluHA:
            replicate_1:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/WT-SI-fluHA-rep1_S2_L001_R1_001.fastq.gz
            replicate_2:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/WT-SI-fluHA-rep2_S3_L001_R1_001.fastq.gz
          fluNA:
            replicate_1:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/WT-SI-fluNA-rep1_S11_L001_R1_001.fastq.gz
            replicate_2:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/WT-SI-fluNA-rep2_S12_L001_R1_001.fastq.gz
        syn:
          fluHA:
            replicate_1:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/dblSyn-SI-fluHA-rep1_S4_L001_R1_001.fastq.gz
            replicate_2:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/dblSyn-SI-fluHA-rep2_S5_L001_R1_001.fastq.gz
          fluNA:
            replicate_1:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/dblSyn-SI-fluNA-rep1_S13_L001_R1_001.fastq.gz
            replicate_2:
              2021-05-17: /shared/ngs/illumina/bloom_lab/210517_M03100_0681_000000000-JL4TM/Data/Intensities/BaseCalls/dblSyn-SI-fluNA-rep2_S14_L001_R1_001.fastq.gz
