name: barcoded_flu_pdmH1N1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair
  - bcbiogff
  - bcbio-nextgen
  - biopython
  - conda-forge::anndata
  - editdistance
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-docstrings
  - flake8-import-order
  - flake8-nb
  - flake8-rst-docstrings
  - git-lfs
  - jupyterlab
  - jupyter_contrib_nbextensions
  - kneed
  - minimap2
  - multiqc
  - nbdime
  - nodejs
  - pandas
  - pbccs>=4.0.0
  - pip
  - plotnine
  - pysam
  - python=3.8
  - pyyaml
  - ruamel.yaml>=0.16
  - samtools
  - scanpy
  - snakemake=5.25
  - sra-tools
  - star
  - svgutils
  - umi_tools
  - pip:
    - alignparse
    - dms_variants
