name: barcoded_flu_pdmH1N1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair
  - bcbiogff
  - bcbio-nextgen
  - biopython
  - conda-forge::anndata
  - git-lfs
  - jupyterlab
  - jupyter_contrib_nbextensions
  - minimap2
  - multiqc
  - nodejs
  - pandas
  - pbccs>=4.0.0
  - pip
  - plotnine
  - pysam
  - python=3.8
  - pyyaml
  - ruamel.yaml>=0.16
  - samtools
  - scanpy
  - snakemake=5.25
  - sra-tools
  - star
  - pip:
    - alignparse
    - dms_variants
